import { Company } from "../store/types";

export const fakeCompanies: Company[] = [
    { id: 1, name: 'ТехноГрупп', address: 'пр. Инноваций, д. 42, г. Техноград', isSelect: false },
    { id: 2, name: 'ЭкоСервис', address: 'ул. Зелёная, д. 15, г. Экорай', isSelect: false },
    { id: 3, name: 'СтройМир', address: 'ул. Строителей, д. 8, г. Стройград', isSelect: false },
    { id: 4, name: 'Инновации', address: 'ул. Новаторов, д. 12, г. Инноваторск', isSelect: false },
    { id: 5, name: 'АгроКомплекс', address: 'ул. Фермерская, д. 20, г. Аграрный', isSelect: false },
    { id: 6, name: 'ФинансГрупп', address: 'ул. Финансовая, д. 5, г. Деньгигород', isSelect: false },
    { id: 7, name: 'ЛогистикаПлюс', address: 'ул. Логистов, д. 3, г. Логистикск', isSelect: false },
    { id: 8, name: 'МедТех', address: 'ул. Здоровья, д. 10, г. Медгород', isSelect: false },
    { id: 9, name: 'КосмоТех', address: 'ул. Космонавтов, д. 7, г. Космоград', isSelect: false },
    { id: 10, name: 'ЭнергоСистемы', address: 'ул. Энергетиков, д. 1, г. Энергоград', isSelect: false },
    { id: 11, name: 'ГлобалТрейд', address: 'ул. Торговая, д. 25, г. Глобалсити', isSelect: false },
    { id: 12, name: 'СуперМаркет', address: 'ул. Продуктовая, д. 30, г. Супергород', isSelect: false },
    { id: 13, name: 'КреативСтудия', address: 'ул. Творческая, д. 18, г. Креативск', isSelect: false },
    { id: 14, name: 'СветТех', address: 'ул. Освещения, д. 22, г. Светоград', isSelect: false },
    { id: 15, name: 'СервисПлюс', address: 'ул. Услуг, д. 4, г. Сервисград', isSelect: false },
    { id: 16, name: 'ДизайнМир', address: 'ул. Дизайнеров, д. 6, г. Дизайнбург', isSelect: false },
    { id: 17, name: 'АвтоГарант', address: 'ул. Автомобилистов, д. 14, г. Автоград', isSelect: false },
    { id: 18, name: 'ТуризмПро', address: 'ул. Туристов, д. 11, г. Туристск', isSelect: false },
    { id: 19, name: 'СпортЛайн', address: 'ул. Спортсменов, д. 9, г. Спортград', isSelect: false },
    { id: 20, name: 'МодаГрупп', address: 'ул. Модная, д. 17, г. Модаград', isSelect: false },
    { id: 21, name: 'Кулинария', address: 'ул. Кулинарная, д. 19, г. Кулинарск', isSelect: false },
    { id: 22, name: 'СтудияИдей', address: 'ул. Идейная, д. 26, г. Идеягород', isSelect: false },
    { id: 23, name: 'ТекноЛаб', address: 'ул. Лабораторная, д. 2, г. Текноград', isSelect: false },
    { id: 24, name: 'АртСалон', address: 'ул. Арт-галереи, д. 27, г. Артгород', isSelect: false },
    { id: 25, name: 'ЗдоровьеПлюс', address: 'ул. Здоровья и Красоты, д. 16, г. Здоровоград', isSelect: false },
    { id: 26, name: 'ЭкспертГрупп', address: 'ул. Экспертов, д. 23, г. Экспертск', isSelect: false },
    { id: 27, name: 'УмныйДом', address: 'ул. Умных технологий, д. 28, г. Умныйгород', isSelect: false },
    { id: 28, name: 'КиберТек', address: 'ул. Кибернетиков, д. 29, г. Киберград', isSelect: false },
    { id: 29, name: 'РемонтСервис', address: 'ул. Ремонтная, д. 31, г. Ремонтоград', isSelect: false },
    { id: 30, name: 'Классика', address: 'ул. Классическая музыка и искусство, д. 32, г. Классикаград', isSelect: false },
    { id: 31, name: 'РесторанГурман', address: 'ул. Гурманская кухня, д. 33, г. Гурманск', isSelect: false },
    { id: 32, name: 'Биотехнологии', address: 'ул. Биотехнологическая, д. 34, г. Биогород', isSelect: false },
    { id: 33, name: 'СтройИнвест', address: 'ул. Инвесторов в стройку, д. 35, г. Инвестград', isSelect: false },
    { id: 34, name: 'ЭкоФерма', address: 'ул. Фермерская экология, д. 36, г. Экофермаград', isSelect: false },
    { id: 35, name: 'ТурбоМоторс', address: 'ул. Моторная индустрия, д. 37, г. Турбоград', isSelect: false },
    { id: 36, name: 'АвиаТех', address: 'ул. Авиационная техника и технологии, д. 38, г. АвиаГрад', isSelect: false },
    { id: 37, name: 'ITСистемы', address: 'ул. IT-решений и технологий, д. 39, г. ITГрад', isSelect: false },
    { id: 38, name: 'Нанотехнологии', address: 'ул. Нанотехнологическая революция, д. 40, г. Наноград', isSelect: false },
    { id: 39, name: 'КосметикСервис', address: 'ул. Косметическая индустрия и услуги, д.41, г.КосметикГрад', isSelect:false},
    { id :40, name:'ФинансовыеРешения', address:' ул . Финансовые услуги, д .43, г . ФинансГрад', isSelect:false},
    { id :41, name:'ТранспортГрупп', address:' ул . Транспортные услуги, д .44, г . ТранспортГрад', isSelect:false},
    { id :42, name:'Промышленность4_0', address:' ул . Промышленные решения, д .45, г . ПромышленностьГрад', isSelect:false},
    { id :43, name:'ЭнергоРесурс', address:' ул . Энергетические ресурсы, д .46, г . ЭнергоГрад', isSelect:false},
    { id :44, name:'УмныеТехнологии', address:' ул . Умные технологии и решения, д .47, г . УмныйГрад', isSelect:false},
    { id :45, name:'ТелекомСистемы', address:' ул . Телекоммуникационные системы, д .48, г . ТелекомГрад', isSelect:false},
    { id :46, name:'АгроИнновации', address:' ул . Инновации в агрономии, д .49, г . АгроГрад', isSelect:false},
    { id :47, name:'БиоЭкология', address:' ул . Экологические технологии и решения, д .50, г . БиоГрад', isSelect:false},
    { id :48, name:'ЭнергетикаБудущего', address:' ул . Будущее энергетики, д .51, г . ЭнергетикаГрад', isSelect:false},
    { id :49, name:'ЦифровыеРешения', address:' ул . Цифровые технологии и решения, д .52, г . ЦифровойГрад', isSelect:false},
    { id :50, name:'ИнновационныйЦентр', address:' ул . Центр инновационных технологий, д .53, г . ИнновационныйГрад', isSelect:false}
];